[[redirects]]
  from = "/u/static/js/*"
  to = "/static/js/:splat"
  status = 200

[[redirects]]
  from = "/u/static/css/*"
  to = "/static/css/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200