version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.15.3

commands:
    npm_install:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: 
                name: Setup Dependencies
                command: npm install
            - save_cache:
                paths:
                    - ./node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
