export interface scoreData{
  difficulty:string,
  version?:string,
  title:string,
  currentBPI:number,
  previousBPI?:number,
  difficultyLevel:string,
  exScore:number,
  previousExScore?:number,
  Pgreat?:number,
  great?:number,
  missCount?:number,
  clearState:number,
  DJLevel:string,
  lastPlayed?:string,
  storedAt:string,
  updatedAt:string,
  isSingle:number,
  isImported?:boolean,
  _isAvailable?:boolean,
}

export interface songData{
  title:string,
  difficulty:string,
  wr:number,
  avg:number,
  notes:number,
  bpm:string,
  textage:string,
  difficultyLevel:string,
  dpLevel:string,
  isFavorited:boolean,
  isCreated:boolean,
  updatedAt:string,
}
